import numpy as np
from pybads import BADS
import json
import os
import subprocess
from pathlib import Path

def get_checkpoint_path(run_idx):
    base = Path("/scratch/hl3976/monkey_4iar/data/harry/processed/modeling/runners/DummyLogistic")
    base.mkdir(parents=True, exist_ok=True)
    return base / f"checkpoint_fold{run_idx}.json"

def dummy_logistic_loss(x):
    # Dummy 3D loss: simulated logistic regression loss on synthetic data
    # Minimized at [1.0, -2.0, 0.5]
    return float(np.sum((x - np.array([1.0, -2.0, 0.5]))**2) * 10 + np.random.randn() * 0.1)

class CheckpointBadsWrapper:
    def __init__(self, run_idx):
        self.run_idx = run_idx
        self.ckpt_path = get_checkpoint_path(run_idx)
        self.best_nll = np.inf
        self.nll_hist = []
        self.iter_hist = []
        self.bads_ref = None

    def obj(self, x):
        loss = dummy_logistic_loss(x)
        if loss < self.best_nll and self.bads_ref is not None:
            self.best_nll = loss
            iter_val = self.bads_ref.optim_state.get("iter", 0)
            self.iter_hist.append(int(iter_val))
            self.nll_hist.append(float(loss))
            
            ckpt = {
                "best_params": x.tolist(),
                "poll_iter": int(iter_val),
                "mesh_size": float(self.bads_ref.optim_state.get("mesh_size", 1.0)),
                "poll_iter_history": self.iter_hist,
                "nll_history": self.nll_hist
            }
            with open(self.ckpt_path, "w") as f:
                json.dump(ckpt, f)
        return loss

def test_dashboard():
    print("Running 3 separate BADS optimizations on dummy logistic regression...")
    lb = np.array([-5, -5, -5])
    ub = np.array([5, 5, 5])
    plb = np.array([-2, -2, -2])
    pub = np.array([2, 2, 2])

    for i in range(3):
        print(f"  Starting Run {i+1} / 3")
        x0 = np.random.uniform(plb, pub)
        wrapper = CheckpointBadsWrapper(i)
        
        bads = BADS(wrapper.obj, x0, lb, ub, plb, pub, options={"display": "none", "max_fun_evals": 100})
        wrapper.bads_ref = bads
        try:
            bads.optimize()
        except ValueError as e:
            if "The key has not been specified" not in str(e):
                raise

    print("\nExecuting fit_monitor.py dashboard...")
    script_path = "/scratch/hl3976/monkey_4iar/scripts/fit_monitor.py"
    plot_file = "/scratch/hl3976/monkey_4iar/scripts/fit_monitor_plot.png"
    if os.path.exists(plot_file):
        os.remove(plot_file)
        
    subprocess.run(["python", script_path, "--datafolder", "/scratch/hl3976/monkey_4iar/data", "--plot_file", plot_file])
    
    assert os.path.exists(plot_file), "Plot file was not generated by fit_monitor.py"
    print(f"\nTest passed! Plot successfully generated at {plot_file}")

if __name__ == "__main__":
    test_dashboard()
